### ISSUE TITLE
Throw a friendly exception when :mailgun_domain and :mailgun_key is not found

### ISSUE THREAD

**Issue by tispratik** [chrismccord/mailgun#30]
This will help newbies understand the problems with mail delivery quickly.

**Comment by davejlong** [comment]
I agree, it took me awhile to figure out that the error:

```
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
    (elixir) lib/io.ex:333: IO.chardata_to_string(nil)
    (elixir) lib/path.ex:467: Path.join/2
    (elixir) lib/path.ex:449: Path.join/1
             lib/client.ex:44: Mailgun.Client.send_without_attachments/2
```

Meant that the API key and domain wasn't set.
